# Generated by Django 3.2 on 2021-04-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default=None, max_length=25)),
                ('item_price', models.IntegerField(default=None)),
                ('item_quantity', models.IntegerField(default=None)),
            ],
        ),
    ]
