# Generated by Django 3.0.14 on 2021-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0003_auto_20210509_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
